language: node_js

node_js:
    - "10"
    - "8"
    - "6"

install:
    - yarn

before_script:
    - yarn run pretest

script:
    - travis_retry yarn test-travis
    - travis_retry yarn bundlesize

after_script:
    - yarn run posttest

jobs:
    include:
        - stage: npm release
          node_js: "8"
          script: yarn release-travis
